name: "Check Conditions Action"
description: "An action to check conditions and output rules_matched"

runs:
  using: "composite"
  steps:
    - id: check
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == 'push' && "${{ github.event.pull_request }}" ]]; then
          run: echo "::set-output name=rules_matched::true"
        else       
          run: echo "::set-output name=rules_matched::false"
        fi
