name: "Check Conditions Action"
description: "An action to check conditions and output rules_matched"

runs:
  using: "composite"
  steps:
    - id: check
      shell: bash
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "Pull request: ${{ github.event.pull_request }}"
        if [[ "${{ github.event_name }}" == 'push' && "${{ github.event.pull_request }}" ]]; then
          echo "::set-output name=rules_matched::true"
        else       
          echo "::set-output name=rules_matched::false"
        fi
        echo "rules_matched set to: ${{ steps.check.outputs.rules_matched }}"
