name: "Check Conditions Action"
description: "An action to check conditions and output rules_matched"

runs:
  using: "composite"
  steps:
    - id: check
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == 'push' && "${{ github.event.pull_request }}" ]]; then
          echo "result=true" >> $GITHUB_ENV
        else
          echo "result=false" >> $GITHUB_ENV
        fi

outputs:
  rules_matched: ${{ env.result }}
