name: Cloud Sync

on:
  push:
  workflow_dispatch:

env:
  INCLUDE_PLATFORMS: 'linux'
  PACKAGE_NAME: 'cloud-sync'
  VDOCS_BUILD_COMMAND: task docs
  VDOCS_DOCS_ORIGIN_PATH: ./docs
  VDOCS_PROJECT_LANGUAGE: python
  VDOCS_PROJECT_DESCRIPTION: "ABM Cloud Sync"
  PYTHON_VERSION: 3.10
      
jobs:  

  build-and-push:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0-dind
        env:
          DOCKER_DRIVER: overlay2
          DOCKER_HOST: tcp://docker:2376
          DOCKER_TLS_CERTDIR: /certs
        options: --privileged
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REG }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t my-image .
          docker tag my-image:latest my-registry/my-image:latest
          docker push my-registry/my-image:latest

  build:
    # Use the latest Ubuntu environment
    runs-on: ubuntu-latest

    # Steps for the job
    steps:
      # Checkout the code
      - name: Check out the repository
        uses: actions/checkout@v3

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t my-app:latest .
        
  # use_poetry_build:
  #   uses: ./.github/workflows/poetry-build.yml
  #   with:
      # PYTHON_VERSION: '3.10'
      # ARTIFACTORY_API_USER: ${{secrets.ARTIFACTORY_API_USER}}
      # ARTIFACTORY_API_TOKEN: ${{secrets.ARTIFACTORY_API_TOKEN}}
      
  # use_Versioned_docs:
  #   uses: ./.github/workflows/versioned-docs.yml
  #   with:
  #     VDOCS_BUILD_COMMAND: $VDOCS_BUILD_COMMAND
  #     VDOCS_DOCS_ORIGIN_PATH: $VDOCS_DOCS_ORIGIN_PATH
  #     VDOCS_PROJECT_LANGUAGE: $VDOCS_PROJECT_LANGUAGE
  #     VDOCS_PROJECT_DESCRIPTION: $VDOCS_PROJECT_DESCRIPTION
  #     PYTHON_VERSION: $PYTHON_VERSION    

    # steps:
    #   - name: Check out code
    #     uses: actions/checkout@v3

    #   - name: Include Poetry Build
    #     uses: rdesingraj/solenis-demo/.github/workflows/poetry-build.yml@main
    #     with:
    #       PYTHON_VERSION: ${{ env.PYTHON_VERSION }}

    #   - name: Include Versioned-Docs
    #     uses: rdesingraj/solenis-demo/.github/workflows/versioned-docs.yml@main
    #     with:
    #       VDOCS_BUILD_COMMAND: $VDOCS_BUILD_COMMAND
    #       VDOCS_DOCS_ORIGIN_PATH: $VDOCS_DOCS_ORIGIN_PATH
    #       VDOCS_PROJECT_LANGUAGE: $VDOCS_PROJECT_LANGUAGE
    #       VDOCS_PROJECT_DESCRIPTION: $VDOCS_PROJECT_DESCRIPTION
    #       PYTHON_VERSION: $PYTHON_VERSION
        
