name: Common Parts Workflow

on: [workflow_call]
jobs:     
  workflow_rules:
    runs-on: ubuntu-latest
    steps:
      - id: check
        run: |
          if [[ "${{ github.event_name }}" == 'push' && "${{ github.event.pull_request }}" ]]; then
            echo "result=true" >> $GITHUB_OUTPUT
          else
            echo "result=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      rules_matched: ${{ steps.check.outputs.result }}
      run: echo "result is ${{ steps.check.outputs.result }}"
        
  # workflow_rules:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     rules_matched: ${{ steps.check.outputs.result }}
  #   steps:
  #     - id: check
  #       run: |
  #         if [[ "${{ github.event_name }}" == 'push' && "${{ github.event.pull_request }}" ]]; then
  #           echo "result=true" >> $GITHUB_OUTPUT
  #         else
  #           echo "result=false" >> $GITHUB_OUTPUT
  #         fi
  semver_tag_rule:
    runs-on: ubuntu-latest
    outputs:
      semver_tag_matched: ${{ steps.check.outputs.result }}
    steps:
      - id: check
        run: |
          if [[ "${{ github.ref }}" =~ ^refs/tags/v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$ ]]; then
            echo "result=true" >> $GITHUB_OUTPUT
          else
            echo "result=false" >> $GITHUB_OUTPUT
          fi
