name: pass-secret-to-workflow
on:
  push:
  workflow_dispatch:
jobs:
  artifactory_container:
    uses: adi-innersource/build-helpers/.github/workflows/artifactory-container.yml@validation-pipeline
    with:
      CI_CONTAINER_REGISTRY: ${{ secrets.ARTIFACTORY_DEFAULT_REGISTRY }}
      CI_CONTAINER_REPO: 'abm/e2e-tests'
