name: Poetry Build

on: [workflow_call]
jobs:
    
  check_conditions:
    runs-on: ubuntu-latest
    outputs:
      rules_matched: ${{ steps.check_conditions_action.outputs.rules_matched }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Check Rule - Workflow
        id: check_conditions_action
        uses: ./.github/actions/workflow-default-action
  
  docs:
    needs: check_conditions
    if: ${{ needs.check_conditions.outputs.workflow != 'true' }}
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Check Rule - Workflow
        id: check_conditions_action
        uses: ./.github/actions/workflow-default-action
      
      - name: Debug Output
        run: |
          echo "Output from check_conditions_action: ${{ needs.check_conditions.outputs.workflow }}"
          echo "Output from check_conditions_action: ${{ env.workflow }}"

      - name: Use the result
        run: | 
          echo "The version is ${{ needs.check_conditions.outputs.workflow }}"
          echo "The version is ${{ env.workflow }}"

  # does:
  #   # runs-on: ubuntu-latest
  #   # needs: check_conditions
  #   # if: ${{ env.rules_matched }} == 'true'
  #   uses: ./.github/workflows/poetry-parts.yml
  #   with:
  #     job: doc_poetry_before_script
  #     PYPI_USERNAME: PYPI_USERNAME
  #     PYPI_TOKEN: PYPI_TOKEN
  #     PYTHON_VERSION: 1
      
      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Install Python and Poetry
      #   id: poetry_installation
      #   uses: ./.github/action/install-poetry
      #   with:
      #     python_version: $PYTHON_VERSION

      # - name: Use Poetry
      #   run: echo ${{ steps.poetry_installation.outputs.poetry_path }}

      # - name: Install Poetry and Docs Dependencies
      #   run: |
      #     ${{ steps.poetry_installation.outputs.poetry_path }}/poetry install --without dev --with docs

  # tests:
  #   # runs-on: ubuntu-latest
  #   needs: check_conditions
  #   if: needs.check_conditions.outputs.rules_matched == 'true'
  #   uses: ./.github/workflows/poetry-parts.yml
  #   with:
  #     job: test_poetry_script
  #     PYPI_USERNAME: PYPI_USERNAME
  #     PYPI_TOKEN: PYPI_TOKEN
  #     PYTHON_VERSION: 1

  # build_linux_x86_64:
  #   # runs-on: ubuntu-latest
  #   needs: check_conditions
  #   if: needs.check_conditions.outputs.rules_matched == 'true'
  #   uses: ./.github/workflows/poetry-parts.yml
  #   with:
  #     job: build_poetry_script
  #     PYPI_USERNAME: PYPI_USERNAME
  #     PYPI_TOKEN: PYPI_TOKEN
  #     PYTHON_VERSION: 1

  # deploy_linux:
  #   # runs-on: ubuntu-latest
  #   needs: [build_linux_x86_64]
  #   if: needs.check_conditions.outputs.rules_matched == 'true'
  #   uses: ./.github/workflows/poetry-parts.yml
  #   with:
  #     PYPI_USERNAME: PYPI_USERNAME
  #     PYPI_TOKEN: PYPI_TOKEN
  #     PYTHON_VERSION: 1
  #     job: deploy_poetry_script
