name: Poetry Build

on: [workflow_call]

jobs:
  check_conditions:
    uses: ./.github/workflows/common-parts.yml
    # outputs:
    #   rules_matched: ${{ jobs.check_conditions.outputs.rules_matched }}

  semver_tag:
    uses: ./.github/workflows/common-parts.yml
    # outputs:
    #   semver_tag_matched: ${{ jobs.semver_tag.outputs.semver_tag_matched }}

  docs:
    # runs-on: ubuntu-latest
    needs: check_conditions
    if: needs.check_conditions.outputs.rules_matched == 'true'
    uses: ./.github/workflows/poetry-parts.yml
    with:
      job: doc_poetry_before_script
      pypi_username: PYPI_USERNAME
      pypi_password: PYPI_PASSWORD
      PYTHON_VERSION: 1

  tests:
    # runs-on: ubuntu-latest
    needs: check_conditions
    if: needs.check_conditions.outputs.rules_matched == 'true'
    uses: ./.github/workflows/poetry-parts.yml
    with:
      job: test_poetry_script
      pypi_username: PYPI_USERNAME
      pypi_password: PYPI_PASSWORD
      PYTHON_VERSION: 1

  build_linux_x86_64:
    # runs-on: ubuntu-latest
    needs: check_conditions
    if: needs.check_conditions.outputs.rules_matched == 'true'
    uses: ./.github/workflows/poetry-parts.yml
    with:
      job: build_poetry_script
      pypi_username: PYPI_USERNAME
      pypi_password: PYPI_PASSWORD
      PYTHON_VERSION: 1

  deploy_linux:
    # runs-on: ubuntu-latest
    needs: [build_linux_x86_64]
    if: needs.check_conditions.outputs.rules_matched == 'true'
    uses: ./.github/workflows/poetry-parts.yml
    with:
      pypi_username: PYPI_USERNAME
      pypi_password: PYPI_PASSWORD
      PYTHON_VERSION: 1
      job: deploy_poetry_script
